import type { Category, Collection, Product, Review } from '../types'

const u = (id: string, w = 1200) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`

/* Image pools by theme (all verified resolving Unsplash imagery) */
export const IMG = {
  shoe: [
    u('1571008887538-b36bb32f4571'),
    u('1549298916-b41d501d3772'),
    u('1595950653106-6c9ebd614d3a'),
    u('1606107557195-0e29a4b5b4aa'),
    u('1542291026-7eec264c27ff'),
    u('1560769629-975ec94e6a86'),
    u('1600185365483-26d7a4cc7519'),
    u('1591047139829-d91aecb6caea'),
  ],
  runner: [
    u('1461896836934-ffe607ba8211'),
    u('1552674605-db6ffd4facb5'),
    u('1520975916090-3105956dac38'),
  ],
  train: [
    u('1534438327276-14e5300c3a48'),
    u('1517836357463-d25dfeac3438'),
    u('1571019613454-1cb2f99b2d8b'),
    u('1518611012118-696072aa579a'),
    u('1556909114-f6e7ad7d3136'),
  ],
  ball: [u('1546519638-68e109498ffc'), u('1504450758481-7338eba7524a')],
  street: [
    u('1576678927484-cc907957088c'),
    u('1515886657613-9f3515b0c78f'),
    u('1521805103424-d8f8430e8933'),
    u('1517438476312-10d79c077509'),
    u('1503341504253-dff4815485f1'),
    u('1543076447-215ad9ba6923'),
    u('1518459031867-a89b944bffe4'),
    u('1574680096145-d05b474e2155'),
    u('1541534741688-6078c6bfb5c5'),
    u('1558611848-73f7eb4001a1'),
    u('1618354691373-d851c5c3a990'),
    u('1571902943202-507ec2618e8f'),
    u('1516726817505-f5ed825624d8'),
    u('1560243563-062bfc001d68'),
    u('1583454110551-21f2fa2afe61'),
    u('1608231387042-66d1773070a5'),
    u('1519167758481-83f550bb49b3'),
  ],
}

export const HERO_IMAGE = u('1552674605-db6ffd4facb5', 1920)
export const OG_IMAGE = u('1552674605-db6ffd4facb5', 1200)

export const categories: Category[] = [
  {
    id: 'cat-running',
    name: 'Running',
    slug: 'running',
    description: 'Performance running shoes and apparel.',
    image: u('1461896836934-ffe607ba8211'),
    sortOrder: 1,
  },
  {
    id: 'cat-training',
    name: 'Training',
    slug: 'training',
    description: 'Training shoes, gym apparel, and accessories.',
    image: u('1534438327276-14e5300c3a48'),
    sortOrder: 2,
  },
  {
    id: 'cat-lifestyle',
    name: 'Lifestyle',
    slug: 'lifestyle',
    description: 'Everyday sneakers and streetwear.',
    image: u('1549298916-b41d501d3772'),
    sortOrder: 3,
  },
  {
    id: 'cat-basketball',
    name: 'Basketball',
    slug: 'basketball',
    description: 'Performance basketball footwear and apparel.',
    image: u('1546519638-68e109498ffc'),
    sortOrder: 4,
  },
]

export const collections: Collection[] = [
  {
    id: 'col-summer-motion',
    name: 'Summer Motion',
    slug: 'summer-motion',
    tagline: 'Built for movement. Designed for everywhere.',
    description:
      'Lightweight layers and breathable performance gear for the hottest months. Engineered to keep you moving from sunrise training to late-night city laps.',
    image: u('1521805103424-d8f8430e8933', 1600),
    dark: false,
    categorySlugs: ['running', 'training'],
    productSlugs: [
      'volt-air-runner',
      'stride-shorts',
      'amplify-tee',
      'aero-flex-trainer',
      'feather-stride',
      'velocity-elite',
    ],
  },
  {
    id: 'col-night-run',
    name: 'Night Run',
    slug: 'night-run',
    tagline: 'Own the streets after dark.',
    description:
      'Reflective detailing, high-visibility colorways and cold-weather protection. Built for the runners who train when the city sleeps.',
    image: u('1552674605-db6ffd4facb5', 1600),
    dark: true,
    categorySlugs: ['running', 'lifestyle'],
    productSlugs: [
      'night-run-jacket',
      'volt-max-pro',
      'zero-gravity',
      'tempest-jacket',
      'pulse-street',
    ],
  },
]

export const products: Product[] = [
  {
    id: 'p-volt-air-runner',
    slug: 'volt-air-runner',
    name: 'Volt Air Runner',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'unisex',
    price: 165,
    compareAtPrice: null,
    rating: 4.8,
    reviewCount: 214,
    description:
      'A featherlight daily trainer built for effortless miles. The Volt Air Runner pairs a nitrogen-infused midsole with a breathable engineered mesh upper for a ride that feels fast from the first step — and stays comfortable at mile 20.',
    images: [IMG.shoe[0], IMG.shoe[3], IMG.runner[0]],
    colors: [
      { name: 'Volt Orange', hex: '#ff4d00' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'White', hex: '#f4f4f2' },
    ],
    sizes: [
      { size: 'US 6', stock: 12 },
      { size: 'US 7', stock: 18 },
      { size: 'US 8', stock: 22 },
      { size: 'US 9', stock: 14 },
      { size: 'US 10', stock: 8 },
      { size: 'US 11', stock: 6 },
      { size: 'US 12', stock: 4 },
    ],
    sku: 'VT-RN-1001',
    technology: ['NitroFoam+ midsole', 'Engineered mesh upper', 'Carbon-reinforced plate'],
    materials: 'Upper: 70% recycled polyester, 30% nylon. Outsole: carbon rubber.',
    fit: 'True to size. Medium width with a snug heel lock.',
    care: ['Remove insoles before washing', 'Air dry away from direct heat', 'Do not machine wash'],
    featured: true,
    trending: true,
    isNew: true,
    collectionIds: ['col-summer-motion', 'col-night-run'],
    tags: ['running', 'daily trainer', 'cushioned', 'road running', 'breathable'],
    createdAt: '2026-06-12T10:00:00Z',
  },
  {
    id: 'p-volt-max-pro',
    slug: 'volt-max-pro',
    name: 'Volt Max Pro',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'unisex',
    price: 190,
    compareAtPrice: 220,
    rating: 4.9,
    reviewCount: 186,
    description:
      'Maximum cushioning, minimum weight. The Volt Max Pro stacks our deepest NitroFoam+ platform with a rockered geometry that propels you forward. Engineered for recovery runs, marathon blocks and every mile in between.',
    images: [IMG.shoe[1], IMG.shoe[5], IMG.runner[2]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Bone', hex: '#e8e2d6' },
      { name: 'Volt Orange', hex: '#ff4d00' },
    ],
    sizes: [
      { size: 'US 6', stock: 0 },
      { size: 'US 7', stock: 9 },
      { size: 'US 8', stock: 16 },
      { size: 'US 9', stock: 20 },
      { size: 'US 10', stock: 11 },
      { size: 'US 11', stock: 7 },
      { size: 'US 12', stock: 3 },
    ],
    sku: 'VT-RN-1002',
    technology: ['NitroFoam+ max stack', 'Rocker geometry', 'Waffle traction outsole'],
    materials: 'Upper: knit mesh with TPU support cage. Outsole: blown rubber.',
    fit: 'True to size. Slightly roomier to accommodate thick running socks.',
    care: ['Spot clean with mild soap', 'Air dry', 'Avoid direct heat'],
    featured: true,
    trending: true,
    isNew: false,
    collectionIds: ['col-night-run'],
    tags: ['running', 'max cushion', 'recovery', 'marathon', 'plush'],
    createdAt: '2026-05-02T10:00:00Z',
  },
  {
    id: 'p-velocity-elite',
    slug: 'velocity-elite',
    name: 'Velocity Elite',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'unisex',
    price: 245,
    compareAtPrice: null,
    rating: 4.7,
    reviewCount: 98,
    description:
      'Our race-day weapon. The Velocity Elite fuses a full-length carbon plate with a super-critical foam core to deliver explosive toe-off and unmatched energy return. Built to chase personal records.',
    images: [IMG.shoe[2], IMG.shoe[6], IMG.runner[1]],
    colors: [
      { name: 'Signal Red', hex: '#e0342c' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'White', hex: '#f4f4f2' },
    ],
    sizes: [
      { size: 'US 6', stock: 5 },
      { size: 'US 7', stock: 12 },
      { size: 'US 8', stock: 14 },
      { size: 'US 9', stock: 0 },
      { size: 'US 10', stock: 10 },
      { size: 'US 11', stock: 6 },
      { size: 'US 12', stock: 2 },
    ],
    sku: 'VT-RN-1003',
    technology: ['Full-length carbon plate', 'Super-critical PEBA foam', 'AtomKnit upper'],
    materials: 'Upper: AtomKnit engineered yarn. Outsole: lightweight rubber pods.',
    fit: 'Racing fit — snug throughout. Size up half a size if between sizes.',
    care: ['Hand wash cold', 'Air dry', 'Do not tumble dry'],
    featured: true,
    trending: false,
    isNew: true,
    collectionIds: ['col-summer-motion'],
    tags: ['running', 'racing', 'carbon plate', 'race day', 'fast'],
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'p-aero-flex-trainer',
    slug: 'aero-flex-trainer',
    name: 'Aero Flex Trainer',
    categoryId: 'cat-training',
    categoryName: 'Training',
    gender: 'unisex',
    price: 145,
    compareAtPrice: null,
    rating: 4.6,
    reviewCount: 152,
    description:
      'A versatile training shoe for every discipline. The Aero Flex Trainer delivers stable lateral support for lifting, flexible forefoot articulation for conditioning, and a grippy flat outsole that locks into every surface.',
    images: [IMG.shoe[4], IMG.train[0], IMG.train[2]],
    colors: [
      { name: 'Charcoal', hex: '#3a3a3a' },
      { name: 'Electric Blue', hex: '#2563eb' },
      { name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { size: 'US 6', stock: 10 },
      { size: 'US 7', stock: 15 },
      { size: 'US 8', stock: 19 },
      { size: 'US 9', stock: 13 },
      { size: 'US 10', stock: 9 },
      { size: 'US 11', stock: 5 },
      { size: 'US 12', stock: 7 },
    ],
    sku: 'VT-TR-2001',
    technology: ['Stability plate', 'Flex-groove outsole', 'Reinforced heel counter'],
    materials: 'Upper: engineered mesh and synthetic overlays. Outsole: full-coverage rubber.',
    fit: 'True to size with a locked-in midfoot.',
    care: ['Wipe with damp cloth', 'Air dry', 'Do not machine wash'],
    featured: true,
    trending: true,
    isNew: false,
    collectionIds: ['col-summer-motion'],
    tags: ['training', 'gym', 'cross training', 'lifting', 'stable'],
    createdAt: '2026-04-18T10:00:00Z',
  },
  {
    id: 'p-pulse-street',
    slug: 'pulse-street',
    name: 'Pulse Street',
    categoryId: 'cat-lifestyle',
    categoryName: 'Lifestyle',
    gender: 'unisex',
    price: 120,
    compareAtPrice: 140,
    rating: 4.5,
    reviewCount: 267,
    description:
      'The everyday sneaker with a pulse. The Pulse Street remixes retro court lines with a modern comfort core — a cushioned midsole, premium leather and a silhouette that goes from studio to street without missing a beat.',
    images: [IMG.shoe[3], IMG.street[0], IMG.street[10]],
    colors: [
      { name: 'White', hex: '#f4f4f2' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Sulfur', hex: '#d9e021' },
    ],
    sizes: [
      { size: 'US 6', stock: 8 },
      { size: 'US 7', stock: 14 },
      { size: 'US 8', stock: 20 },
      { size: 'US 9', stock: 25 },
      { size: 'US 10', stock: 18 },
      { size: 'US 11', stock: 12 },
      { size: 'US 12', stock: 0 },
    ],
    sku: 'VT-LS-3001',
    technology: ['CloudStep midsole', 'Premium full-grain leather', 'Padded collar'],
    materials: 'Upper: full-grain leather. Lining: textile. Outsole: gum rubber.',
    fit: 'True to size. Wide-foot friendly.',
    care: ['Wipe with damp cloth', 'Use leather cleaner for marks', 'Air dry'],
    featured: false,
    trending: true,
    isNew: false,
    collectionIds: ['col-night-run'],
    tags: ['lifestyle', 'sneaker', 'streetwear', 'casual', 'leather'],
    createdAt: '2026-03-22T10:00:00Z',
  },
  {
    id: 'p-core-motion',
    slug: 'core-motion',
    name: 'Core Motion Tee',
    categoryId: 'cat-training',
    categoryName: 'Training',
    gender: 'men',
    price: 45,
    compareAtPrice: null,
    rating: 4.4,
    reviewCount: 89,
    description:
      'A four-way stretch training tee built to move with you. The Core Motion Tee uses quick-dry fabric with targeted ventilation panels to keep you cool through the heaviest sessions.',
    images: [IMG.train[2], IMG.train[4], IMG.street[2]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'White', hex: '#f4f4f2' },
      { name: 'Volt Orange', hex: '#ff4d00' },
    ],
    sizes: [
      { size: 'XS', stock: 10 },
      { size: 'S', stock: 16 },
      { size: 'M', stock: 24 },
      { size: 'L', stock: 20 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 6 },
    ],
    sku: 'VT-TR-2002',
    technology: ['Quick-dry fabric', 'Ventilation mesh panels', 'Anti-odor treatment'],
    materials: '88% recycled polyester, 12% spandex.',
    fit: 'Athletic fit — trimmed through the body.',
    care: ['Machine wash cold', 'Do not use fabric softener', 'Tumble dry low'],
    featured: false,
    trending: true,
    isNew: true,
    collectionIds: ['col-summer-motion'],
    tags: ['training', 'tee', 'gym', 'quick dry', 'men'],
    createdAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'p-night-run-jacket',
    slug: 'night-run-jacket',
    name: 'Night Run Jacket',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'unisex',
    price: 130,
    compareAtPrice: null,
    rating: 4.8,
    reviewCount: 73,
    description:
      'Engineered for visibility. The Night Run Jacket packs 360° reflective detailing, a water-repellent shell and packable construction into a featherlight layer designed for after-dark miles.',
    images: [IMG.runner[1], IMG.street[6], IMG.street[13]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Volt Orange', hex: '#ff4d00' },
      { name: 'Midnight', hex: '#16213e' },
    ],
    sizes: [
      { size: 'XS', stock: 0 },
      { size: 'S', stock: 9 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 7 },
      { size: 'XXL', stock: 4 },
    ],
    sku: 'VT-RN-1004',
    technology: ['360° reflective trim', 'DWR water-repellent shell', 'Packable into own pocket'],
    materials: 'Shell: 100% recycled ripstop nylon. Lining: breathable mesh.',
    fit: 'Streamlined running fit with drop-tail hem.',
    care: ['Machine wash cold', 'Hang dry', 'Do not iron reflective panels'],
    featured: true,
    trending: true,
    isNew: false,
    collectionIds: ['col-night-run'],
    tags: ['running', 'jacket', 'reflective', 'night run', 'water repellent'],
    createdAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'p-stride-shorts',
    slug: 'stride-shorts',
    name: 'Stride Shorts 5"',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'men',
    price: 50,
    compareAtPrice: null,
    rating: 4.5,
    reviewCount: 121,
    description:
      'Featherlight running shorts with a liner-free design, secure zip pocket and sweat-wicking fabric. The 5" inseam keeps you free for tempo days and track sessions.',
    images: [IMG.runner[2], IMG.street[4], IMG.street[14]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Light Gray', hex: '#c9c9c4' },
      { name: 'Electric Blue', hex: '#2563eb' },
    ],
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 15 },
      { size: 'M', stock: 22 },
      { size: 'L', stock: 18 },
      { size: 'XL', stock: 9 },
      { size: 'XXL', stock: 0 },
    ],
    sku: 'VT-RN-1005',
    technology: ['Sweat-wicking fabric', 'Secure zip back pocket', 'Reflective logo'],
    materials: '100% recycled polyester with moisture-wicking finish.',
    fit: 'Standard fit with elastic waistband and drawcord.',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not iron'],
    featured: false,
    trending: false,
    isNew: false,
    collectionIds: ['col-summer-motion'],
    tags: ['running', 'shorts', 'summer', 'track', 'men'],
    createdAt: '2026-05-30T10:00:00Z',
  },
  {
    id: 'p-amplify-tee',
    slug: 'amplify-tee',
    name: 'Amplify Run Tee',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'women',
    price: 40,
    compareAtPrice: null,
    rating: 4.6,
    reviewCount: 84,
    description:
      'A second-skin running tee with a soft-touch recycled knit, bonded seams and a drop-tail hem. The Amplify Tee disappears on your body so you can focus on the road ahead.',
    images: [IMG.train[3], IMG.street[5], IMG.street[15]],
    colors: [
      { name: 'Bone', hex: '#e8e2d6' },
      { name: 'Coral', hex: '#ff6b57' },
      { name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { size: 'XS', stock: 12 },
      { size: 'S', stock: 18 },
      { size: 'M', stock: 20 },
      { size: 'L', stock: 11 },
      { size: 'XL', stock: 5 },
      { size: 'XXL', stock: 3 },
    ],
    sku: 'VT-RN-1006',
    technology: ['Bonded seams', 'Soft-touch recycled knit', 'Moisture-wicking finish'],
    materials: '78% recycled polyester, 22% spandex.',
    fit: 'Slim, second-skin fit.',
    care: ['Machine wash cold', 'Air dry', 'Do not iron logos'],
    featured: false,
    trending: true,
    isNew: true,
    collectionIds: ['col-summer-motion'],
    tags: ['running', 'tee', 'women', 'second skin', 'breathable'],
    createdAt: '2026-06-28T10:00:00Z',
  },
  {
    id: 'p-court-surge',
    slug: 'court-surge',
    name: 'Court Surge',
    categoryId: 'cat-basketball',
    categoryName: 'Basketball',
    gender: 'unisex',
    price: 175,
    compareAtPrice: 195,
    rating: 4.7,
    reviewCount: 143,
    description:
      'Built to explode. The Court Surge wraps your foot in a lockdown fit system with responsive heel cushioning and a herringbone outsole that grips the hardwood through every cut, jump and landing.',
    images: [IMG.ball[0], IMG.shoe[7], IMG.ball[1]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Signal Red', hex: '#e0342c' },
      { name: 'White', hex: '#f4f4f2' },
    ],
    sizes: [
      { size: 'US 6', stock: 6 },
      { size: 'US 7', stock: 11 },
      { size: 'US 8', stock: 17 },
      { size: 'US 9', stock: 15 },
      { size: 'US 10', stock: 9 },
      { size: 'US 11', stock: 0 },
      { size: 'US 12', stock: 5 },
    ],
    sku: 'VT-BB-4001',
    technology: ['Lockdown fit system', 'Responsive heel foam', 'Herringbone traction'],
    materials: 'Upper: knit with fused overlays. Outsole: high-abrasion rubber.',
    fit: 'True to size with a snug, secure fit.',
    care: ['Wipe with damp cloth', 'Air dry', 'Store at room temperature'],
    featured: true,
    trending: true,
    isNew: false,
    collectionIds: [],
    tags: ['basketball', 'court', 'hoops', 'performance', 'grip'],
    createdAt: '2026-04-05T10:00:00Z',
  },
  {
    id: 'p-zero-gravity',
    slug: 'zero-gravity',
    name: 'Zero Gravity Runner',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'unisex',
    price: 155,
    compareAtPrice: null,
    rating: 4.6,
    reviewCount: 67,
    description:
      'Float over any surface. The Zero Gravity Runner pairs a dual-density midsole with a grippy trail-ready outsole, making it equally at home on pavement, gravel and groomed trails.',
    images: [IMG.shoe[5], IMG.runner[2], IMG.shoe[2]],
    colors: [
      { name: 'Forest Green', hex: '#1f5c3d' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Volt Orange', hex: '#ff4d00' },
    ],
    sizes: [
      { size: 'US 6', stock: 4 },
      { size: 'US 7', stock: 10 },
      { size: 'US 8', stock: 13 },
      { size: 'US 9', stock: 16 },
      { size: 'US 10', stock: 8 },
      { size: 'US 11', stock: 6 },
      { size: 'US 12', stock: 2 },
    ],
    sku: 'VT-RN-1007',
    technology: ['Dual-density midsole', 'Trail-grip outsole', 'Rock shield'],
    materials: 'Upper: ripstop mesh. Outsole: multi-directional lugs.',
    fit: 'True to size. Roomy toe box.',
    care: ['Brush off dirt after runs', 'Air dry', 'Do not machine wash'],
    featured: false,
    trending: false,
    isNew: true,
    collectionIds: ['col-night-run'],
    tags: ['running', 'trail', 'hybrid', 'gravel', 'cushioned'],
    createdAt: '2026-07-10T10:00:00Z',
  },
  {
    id: 'p-tempest-jacket',
    slug: 'tempest-jacket',
    name: 'Tempest Shell Jacket',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'women',
    price: 140,
    compareAtPrice: null,
    rating: 4.7,
    reviewCount: 42,
    description:
      'Storm-proof, motion-ready. The Tempest Shell uses a fully seam-sealed waterproof membrane with articulated sleeves and a helmet-compatible hood — protection that never slows you down.',
    images: [IMG.street[8], IMG.runner[1], IMG.street[9]],
    colors: [
      { name: 'Midnight', hex: '#16213e' },
      { name: 'Coral', hex: '#ff6b57' },
      { name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { size: 'XS', stock: 7 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 9 },
      { size: 'XL', stock: 4 },
      { size: 'XXL', stock: 0 },
    ],
    sku: 'VT-RN-1008',
    technology: ['Seam-sealed waterproof membrane', 'Articulated sleeves', 'Adjustable hood'],
    materials: 'Shell: 100% recycled polyester with waterproof membrane.',
    fit: 'Athletic fit with room for light layers.',
    care: ['Machine wash cold', 'Hang dry', 'Reapply DWR as needed'],
    featured: false,
    trending: false,
    isNew: true,
    collectionIds: ['col-night-run'],
    tags: ['running', 'jacket', 'waterproof', 'rain', 'women'],
    createdAt: '2026-07-18T10:00:00Z',
  },
  {
    id: 'p-kinetic-legging',
    slug: 'kinetic-legging',
    name: 'Kinetic High-Rise Legging',
    categoryId: 'cat-training',
    categoryName: 'Training',
    gender: 'women',
    price: 78,
    compareAtPrice: 90,
    rating: 4.8,
    reviewCount: 158,
    description:
      'Sculpting support with total freedom of movement. The Kinetic Legging features a high-rise waistband, squat-proof fabric and a hidden phone pocket — engineered to stay in place through every rep.',
    images: [IMG.train[3], IMG.street[12], IMG.train[1]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Forest Green', hex: '#1f5c3d' },
      { name: 'Charcoal', hex: '#3a3a3a' },
    ],
    sizes: [
      { size: 'XS', stock: 14 },
      { size: 'S', stock: 20 },
      { size: 'M', stock: 18 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 6 },
      { size: 'XXL', stock: 4 },
    ],
    sku: 'VT-TR-2003',
    technology: ['Squat-proof compression', 'Hidden phone pocket', 'Flatlock seams'],
    materials: '75% recycled nylon, 25% elastane.',
    fit: 'High-rise, true to size. Compression fit.',
    care: ['Machine wash cold', 'Do not use fabric softener', 'Hang dry'],
    featured: false,
    trending: true,
    isNew: false,
    collectionIds: ['col-summer-motion'],
    tags: ['training', 'legging', 'women', 'gym', 'compression'],
    createdAt: '2026-05-12T10:00:00Z',
  },
  {
    id: 'p-rebound-hoodie',
    slug: 'rebound-hoodie',
    name: 'Rebound Hoodie',
    categoryId: 'cat-lifestyle',
    categoryName: 'Lifestyle',
    gender: 'unisex',
    price: 85,
    compareAtPrice: null,
    rating: 4.6,
    reviewCount: 95,
    description:
      'A heavyweight streetwear essential. The Rebound Hoodie is cut from 450gsm loopback fleece with a dropped shoulder, ribbed side panels and a kangaroo pocket built for the everyday.',
    images: [IMG.street[3], IMG.street[16], IMG.street[7]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Bone', hex: '#e8e2d6' },
      { name: 'Volt Orange', hex: '#ff4d00' },
    ],
    sizes: [
      { size: 'XS', stock: 9 },
      { size: 'S', stock: 15 },
      { size: 'M', stock: 21 },
      { size: 'L', stock: 17 },
      { size: 'XL', stock: 10 },
      { size: 'XXL', stock: 5 },
    ],
    sku: 'VT-LS-3002',
    technology: ['450gsm loopback fleece', 'Ribbed side panels', 'Dropped shoulder'],
    materials: '80% organic cotton, 20% recycled polyester.',
    fit: 'Relaxed, oversized fit.',
    care: ['Machine wash cold', 'Tumble dry low', 'Wash inside out'],
    featured: false,
    trending: true,
    isNew: false,
    collectionIds: [],
    tags: ['lifestyle', 'hoodie', 'streetwear', 'fleece', 'unisex'],
    createdAt: '2026-03-08T10:00:00Z',
  },
  {
    id: 'p-feather-stride',
    slug: 'feather-stride',
    name: 'Feather Stride',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'women',
    price: 160,
    compareAtPrice: null,
    rating: 4.8,
    reviewCount: 76,
    description:
      'Weightless cushioning engineered for the female foot. The Feather Stride uses a gender-tuned foam distribution and a narrower heel geometry for a smooth, responsive ride on every run.',
    images: [IMG.shoe[6], IMG.shoe[0], IMG.runner[2]],
    colors: [
      { name: 'White', hex: '#f4f4f2' },
      { name: 'Coral', hex: '#ff6b57' },
      { name: 'Bone', hex: '#e8e2d6' },
    ],
    sizes: [
      { size: 'US 6', stock: 16 },
      { size: 'US 7', stock: 20 },
      { size: 'US 8', stock: 12 },
      { size: 'US 9', stock: 9 },
      { size: 'US 10', stock: 4 },
      { size: 'US 11', stock: 3 },
      { size: 'US 12', stock: 1 },
    ],
    sku: 'VT-RN-1009',
    technology: ['Gender-tuned foam', 'Narrower heel geometry', 'Breathable mesh upper'],
    materials: 'Upper: recycled mesh. Outsole: carbon rubber.',
    fit: 'True to size. Narrower through the heel.',
    care: ['Remove insoles before washing', 'Air dry', 'Do not machine wash'],
    featured: true,
    trending: true,
    isNew: true,
    collectionIds: ['col-summer-motion'],
    tags: ['running', 'women', 'daily trainer', 'lightweight', 'cushioned'],
    createdAt: '2026-06-05T10:00:00Z',
  },
  {
    id: 'p-flex-knit-pant',
    slug: 'flex-knit-pant',
    name: 'Flex Knit Training Pant',
    categoryId: 'cat-training',
    categoryName: 'Training',
    gender: 'men',
    price: 70,
    compareAtPrice: null,
    rating: 4.4,
    reviewCount: 58,
    description:
      'Warm-up or cool-down, the Flex Knit Pant moves with you. A brushed knit interior, tapered leg and zip ankle cuffs make layering effortless from the gym to the street.',
    images: [IMG.train[1], IMG.street[11], IMG.train[0]],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Graphite', hex: '#4a4a4a' },
      { name: 'Midnight', hex: '#16213e' },
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 13 },
      { size: 'M', stock: 19 },
      { size: 'L', stock: 16 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 3 },
    ],
    sku: 'VT-TR-2004',
    technology: ['Brushed knit interior', 'Tapered leg', 'Zip ankle cuffs'],
    materials: '70% recycled polyester, 30% cotton.',
    fit: 'Regular fit, tapered through the leg.',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not iron'],
    featured: false,
    trending: false,
    isNew: false,
    collectionIds: [],
    tags: ['training', 'pants', 'gym', 'jogger', 'men'],
    createdAt: '2026-04-22T10:00:00Z',
  },
  {
    id: 'p-metro-classic',
    slug: 'metro-classic',
    name: 'Metro Classic Low',
    categoryId: 'cat-lifestyle',
    categoryName: 'Lifestyle',
    gender: 'unisex',
    price: 105,
    compareAtPrice: 120,
    rating: 4.3,
    reviewCount: 203,
    description:
      'A timeless low-top silhouette with a modern comfort core. The Metro Classic Low is finished in premium suede with a vulcanized sole — the clean canvas for every rotation.',
    images: [IMG.shoe[7], IMG.street[1], IMG.street[2]],
    colors: [
      { name: 'White', hex: '#f4f4f2' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Light Gray', hex: '#c9c9c4' },
    ],
    sizes: [
      { size: 'US 6', stock: 12 },
      { size: 'US 7', stock: 18 },
      { size: 'US 8', stock: 22 },
      { size: 'US 9', stock: 24 },
      { size: 'US 10', stock: 15 },
      { size: 'US 11', stock: 9 },
      { size: 'US 12', stock: 6 },
    ],
    sku: 'VT-LS-3003',
    technology: ['CloudStep comfort core', 'Vulcanized sole', 'Premium suede upper'],
    materials: 'Upper: premium suede. Lining: textile. Outsole: vulcanized rubber.',
    fit: 'True to size. Medium width.',
    care: ['Use suede brush', 'Protect with suede spray', 'Air dry'],
    featured: false,
    trending: false,
    isNew: false,
    collectionIds: [],
    tags: ['lifestyle', 'sneaker', 'suede', 'classic', 'low top'],
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'p-volt-air-runner-kids',
    slug: 'volt-air-runner-kids',
    name: 'Volt Air Runner Kids',
    categoryId: 'cat-running',
    categoryName: 'Running',
    gender: 'kids',
    price: 95,
    compareAtPrice: null,
    rating: 4.7,
    reviewCount: 34,
    description:
      'All the speed, sized for the next generation. The Volt Air Runner Kids brings our signature lightweight cushioning to growing feet with a roomier toe box and easy hook-and-loop options on smaller sizes.',
    images: [IMG.shoe[0], IMG.street[4], IMG.runner[0]],
    colors: [
      { name: 'Volt Orange', hex: '#ff4d00' },
      { name: 'Electric Blue', hex: '#2563eb' },
      { name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { size: 'S 10C', stock: 10 },
      { size: 'S 11C', stock: 14 },
      { size: 'S 12C', stock: 12 },
      { size: 'S 1Y', stock: 9 },
      { size: 'S 2Y', stock: 7 },
      { size: 'S 3Y', stock: 4 },
    ],
    sku: 'VT-RN-1010',
    technology: ['Kid-tuned cushioning', 'Roomier toe box', 'Easy closure options'],
    materials: 'Upper: recycled mesh. Outsole: durable rubber.',
    fit: 'Roomier fit for growing feet.',
    care: ['Wipe with damp cloth', 'Air dry', 'Do not machine wash'],
    featured: false,
    trending: false,
    isNew: true,
    collectionIds: [],
    tags: ['running', 'kids', 'school', 'play', 'lightweight'],
    createdAt: '2026-07-05T10:00:00Z',
  },
]

const seedReviews: Array<Omit<Review, 'id' | 'productId'>> = [
  {
    userName: 'Maya R.',
    rating: 5,
    title: 'Best daily trainer I\'ve owned',
    body: 'The cushioning is perfect — soft enough for long runs but responsive when I pick up the pace. Zero break-in period.',
    date: '2026-07-22',
    verified: true,
  },
  {
    userName: 'Devon K.',
    rating: 5,
    title: 'Feels like running on air',
    body: 'Ordered true to size and the fit is dialed. The upper breathes really well on hot summer miles.',
    date: '2026-07-15',
    verified: true,
  },
  {
    userName: 'Priya S.',
    rating: 4,
    title: 'Great shoe, slightly snug',
    body: 'Quality is excellent. I would size up half a size if you have wide feet. Otherwise fantastic.',
    date: '2026-06-30',
    verified: true,
  },
  {
    userName: 'Tom W.',
    rating: 5,
    title: 'Race day magic',
    body: 'The carbon plate gives you that extra pop. Set a 10K PR on the first run.',
    date: '2026-07-18',
    verified: true,
  },
  {
    userName: 'Alicia M.',
    rating: 4,
    title: 'Solid all-rounder',
    body: 'Stable for lifting and flexible for conditioning. Grip is excellent on every surface I\'ve tried.',
    date: '2026-06-11',
    verified: true,
  },
  {
    userName: 'Jonah T.',
    rating: 5,
    title: 'My go-to sneaker',
    body: 'Comfortable from day one and they look incredible. Get compliments every time I wear them.',
    date: '2026-07-02',
    verified: true,
  },
  {
    userName: 'Sarah L.',
    rating: 5,
    title: 'Invisible on your body',
    body: 'Lightest tee I own. The fabric is incredibly soft and it dries in minutes.',
    date: '2026-07-09',
    verified: true,
  },
  {
    userName: 'Marcus B.',
    rating: 5,
    title: 'Safest night runs',
    body: 'The reflectivity is unreal — cars see you from way off. Packs down tiny for storage.',
    date: '2026-06-24',
    verified: true,
  },
  {
    userName: 'Elena V.',
    rating: 5,
    title: 'Perfect fit for training',
    body: 'Stay up during squats, no see-through, and the phone pocket actually holds my phone securely.',
    date: '2026-07-20',
    verified: true,
  },
]

export function buildSeedReviews(): Review[] {
  const list: Review[] = []
  const productIds = [
    'p-volt-air-runner',
    'p-volt-max-pro',
    'p-velocity-elite',
    'p-aero-flex-trainer',
    'p-pulse-street',
    'p-night-run-jacket',
    'p-kinetic-legging',
  ]
  let n = 0
  for (const pid of productIds) {
    for (const r of seedReviews.slice(n % seedReviews.length, n % seedReviews.length + 3)) {
      list.push({
        id: `rev-${pid}-${list.length}`,
        productId: pid,
        ...r,
      })
    }
    n += 3
  }
  return list
}

export const SITE_COPY = {
  heroHeadline: 'MOVE WITHOUT LIMITS',
  heroSub: 'Performance engineered for every version of you.',
}
